- op: replace
  path: /users
  value:
    - jdemoss
    - cgoern
    - azaalouk
    - kecook
    - jzarecki
    - mfentane
    - pedouble
    - abellusc
    - tkatarki
    - linglis
    - jepandit
    - yyi
    - asaluja
    - wcabanba
    - naisingh
    - rogreenb
    - yfama
    - egallen
    - jofernan
    - gshipley
    - dacolema
    - egranger
    - mlovett
    - rguntrip
    - szelenov
    - tasmith
    - jharmiso
    - mhepburn
    - flavigne
    - cnuland
    - rlundber
    - ckavili
    - abanderb
    - rcarrata
    - keklund
    - gmoutier
    - phayes

