apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/cfchase/rhoai-nightly
        revision: main
        directories:
          - path: components/operators/*
  template:
    metadata:
      name: 'operator-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/cfchase/rhoai-nightly
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          selfHeal: true
