apiVersion: infrastructure.opendatahub.io/v1
kind: HardwareProfile
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    opendatahub.io/dashboard-feature-visibility: '[]'
    opendatahub.io/description: GPU profile with 1 CPU, 12 GiB memory, and 1 NVIDIA GPU.
    opendatahub.io/disabled: 'false'
    opendatahub.io/display-name: GPU Profile
  labels:
    app.kubernetes.io/part-of: hardwareprofile
    app.opendatahub.io/hardwareprofile: "true"
  name: gpu-profile
  namespace: redhat-ods-applications
spec:
  identifiers:
    - defaultCount: '1'
      displayName: CPU
      identifier: cpu
      minCount: 1
      resourceType: CPU
    - defaultCount: 12Gi
      displayName: Memory
      identifier: memory
      minCount: 1Gi
      resourceType: Memory
    - defaultCount: 1
      displayName: GPU
      identifier: nvidia.com/gpu
      minCount: 1
      resourceType: Accelerator
