apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-operators-applicationset
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  syncPolicy:
    applicationsSync: create-only
  generators:
    - git:
        repoURL: https://github.com/rh-aiservices-bu/rhoai-nightly
        revision: main
        directories:
          - path: components/operators/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      syncPolicy: {}
      ignoreDifferences:
        - group: operators.coreos.com
          kind: Subscription
          jsonPointers:
            - /spec/installPlanApproval
      source:
        repoURL: https://github.com/rh-aiservices-bu/rhoai-nightly
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
