apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-oper-instances-applicationset
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  generators:
    - list:
        elements:
          - cluster: local
            values:
              name: instance-nfd
              path: components/instances/nfd-instance/overlays/nvidia
              namespace: openshift-gitops
  template:
    metadata:
      name: "{{values.name}}"
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
    spec:
      project: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
      source:
        repoURL: https://github.com/cfchase/rhoai-nightly
        targetRevision: main
        path: "{{values.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
