apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: banner-nightly
spec:
  text: "RHOAI 3.4 Nightly Build - Apr 21, 2026"
  location: BannerTop
  color: "#FFF"
  backgroundColor: "#0066CC"
